// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR1fzL9z6gwGFO-h8B28fsu2GjJqzGd14',
    appId: '1:55152636706:web:b202c68e801973c380ab7b',
    messagingSenderId: '55152636706',
    projectId: 'coffee-shop-17198',
    authDomain: 'coffee-shop-17198.firebaseapp.com',
    storageBucket: 'coffee-shop-17198.appspot.com',
    measurementId: 'G-6BJ8TCPTCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg8riX3f7fXVbFQF0M20d5eizapSPIorE',
    appId: '1:55152636706:android:663197bef05c44a680ab7b',
    messagingSenderId: '55152636706',
    projectId: 'coffee-shop-17198',
    storageBucket: 'coffee-shop-17198.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbkCFqfBJzCOs-RPRMx0NdgN8ZJLDwj58',
    appId: '1:55152636706:ios:1bbdf1f73f63fe3180ab7b',
    messagingSenderId: '55152636706',
    projectId: 'coffee-shop-17198',
    storageBucket: 'coffee-shop-17198.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbkCFqfBJzCOs-RPRMx0NdgN8ZJLDwj58',
    appId: '1:55152636706:ios:1bbdf1f73f63fe3180ab7b',
    messagingSenderId: '55152636706',
    projectId: 'coffee-shop-17198',
    storageBucket: 'coffee-shop-17198.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR1fzL9z6gwGFO-h8B28fsu2GjJqzGd14',
    appId: '1:55152636706:web:81bc1bd0f0edde8d80ab7b',
    messagingSenderId: '55152636706',
    projectId: 'coffee-shop-17198',
    authDomain: 'coffee-shop-17198.firebaseapp.com',
    storageBucket: 'coffee-shop-17198.appspot.com',
    measurementId: 'G-1T0M4PJBVG',
  );
}
